### ISSUE TITLE
BelongsToMany shows item id as option title

### ISSUE THREAD

**Issue by krisis32** [optimistdigital/nova-multiselect-field#110]
On belongstomany select, option title is set to id. Is there any way to change it to get actual title?
Can also search only using id numbers.
<img width="439" alt="Screenshot 2021-06-21 at 12 15 36 PM" src="https://user-images.githubusercontent.com/1643150/122738269-85615380-d28a-11eb-817f-df34ccb888df.png">

**Comment by Tarpsvo** [comment]
The options use Nova's default Title behaviour.

See the docs here:
https://nova.laravel.com/docs/3.0/search/global-search.html#title-subtitle-attributes

You could either
a) Set the `public static $title = 'name';` property on the Resource to set which property is used as the title.
b) Override the `public function title()` method and return a customized name for the model.

Good luck!
