### ISSUE TITLE
saveAsJson( true ) but get an array stringified

### ISSUE THREAD

**Issue by mikeanan** [optimistdigital/nova-multiselect-field#111]
Hi, @Tarpsvo,

I read some issues from the list:
@mstaack's https://github.com/optimistdigital/nova-multiselect-field/issues/64#issuecomment-687080583_
@mattyh88's https://github.com/optimistdigital/nova-multiselect-field/issues/36#issuecomment-615840908
And also follow @tousif786's example code --> https://github.com/optimistdigital/nova-multiselect-field/issues/61
and also set saveAsJson(true), but I get an array stringified -->  [ "a", "b", "c" ] not like @tousif786's json type: {"data": null, "role": null}.

Any suggestion?

**Comment by Tarpsvo** [comment]
In what context are you using this? Just inside a regular Nova resource and not wrapped inside any other fields?

**Comment by Tarpsvo** [comment]
I see that you're using it inside Nova Menu Builder?

I ran a quick test myself with the following menu item type:

```
    public static function getFields(): array
    {
        return [
            Text::make('Test', 'test'),
            Multiselect::make('Tracks', 'tracks')
                ->options(Track::all()->pluck('name', 'id')->toArray())
                ->saveAsJSON(true),
            Multiselect::make('Artists', 'artists')
                ->options(Artist::all()->pluck('name', 'id')->toArray())
                ->saveAsJSON(true),
        ];
    }
```

And it saves it correctly:
![image](https://user-images.githubusercontent.com/2018660/124443855-b52e5200-dd86-11eb-9c81-71b1af67b294.png)


I'm afraid I need more info to be able to debug your issue. :S
