### ISSUE TITLE
BelongsToMany - Depends on other MultiSelect

### ISSUE THREAD

**Issue by airdev-web** [optimistdigital/nova-multiselect-field#113]
Hello again !

Here is a my db situation :
```
teams table
 - id
 - title

users table
 - id
 - name

user_teams table
 - id
 - user_id
 - team_id
```

My idea is to have 1 Multiselect field that contains the differents Teams. And Depend of the selected team, I want to show the users that belongs to this team.

I thought of this idea, but the list of the 'users' multiselect still empty.
```php
Multiselect::make('Selected team', 'team')
    ->belongsTo(TeamRessource::class, false),

Multiselect::make('Users of this team', 'users')
    ->dependsOn('team')
    ->belongsToMany(User::class, false),
```

So I thought that I can use `->dependsOnOptions(array)` method, but it takes an array in parameters, and not really a callback that maybe will have in parameters the selected team model of the first multiselect field?

I have of course in my models

```php
// Teams.php
public function users()
{
    return $this->belongsToMany(User::class, 'intervention_users');
}

// Users.php
public function teams()
{
    return $this->belongsToMany(Team::class, 'user_teams');
}
```

Is this possible ?

**Comment by Tarpsvo** [comment]
Hi! Unfortunately, it's not possible and I doubt support for it will be ever added. :(
