### ISSUE TITLE
Random JS broken

### ISSUE THREAD

**Issue by antoniodisanto92** [optimistdigital/nova-multiselect-field#117]
Hi @Tarpsvo ,

I have an issue with JS of the library. It randomly gives a `Uncaught SyntaxError: Unexpected identifier in multiselect-field:2`, but being minified it's impossible to understand it.
In local machine works correctly. Same environment online, but using Docker, gives me this issue.

PHP 7.3-fpm as Docker image
NodeJS (local) v14.17.5
NodeJS (in docker) v14.17.5
Docker version 20.10.3, build 48d30b5
Nova installed internally as Directory, v3.20.0
MySQL v5.7.22

Component is used like this:
```
Multiselect::make('Incoming roles', 'incoming_roles')
                ->showOnCreating(false)
                ->showOnIndex(false)
                ->options($roles) // array, ['role 1' => 'role 1', 'role 2' => 'role 2', ...]
                ->placeholder('Choose roles')
                ->saveAsJSON() // column is saved as json
                ->optionsLimit(10)
                ->reorderable(),
```

If you need further info, let me know.

**Comment by Tarpsvo** [comment]
Hi @antoniodisanto92. Sorry for the long delay, but I'm now trying to catch up on all my open source issues.

Did you ever find the cause? Currently, I don't have any idea why it would act like this. I deploy all my live projects using Docker and never have I encountered this issue.

Especially it shouldn't make a difference because it's pre-compiled and it seems like the JavaScript has an issue with the response. Are you sure the server is returning valid JavaScript not some HTML error page?

**Comment by antoniodisanto92** [comment]
Unfortunately no. But if I set the APP_ENV to DEVELOPMENT gives no errors and works correctly.

**Comment by Tarpsvo** [comment]
Can you send a screenshot of what ```https://cms.nova.test/nova-api/scripts/multiselect-field``` route returns?

**Comment by antoniodisanto92** [comment]
<img width="512" alt="Schermata 2021-09-02 alle 16 32 58" src="https://user-images.githubusercontent.com/5053011/131863000-7724294d-7c89-4057-a530-32476d66f2cb.png">
<img width="449" alt="Schermata 2021-09-02 alle 16 33 30" src="https://user-images.githubusercontent.com/5053011/131863013-2d72911e-7644-43e8-9c49-d100e929d16f.png">
<img width="413" alt="Schermata 2021-09-02 alle 16 33 23" src="https://user-images.githubusercontent.com/5053011/131863023-c55467c9-c2e4-4b85-a98e-60e6ea2cdda8.png">

**Comment by Tarpsvo** [comment]
That's indeed really weird. Your production environment seems to return invalid JavaScript indeed. My code looks like this:
![image](https://user-images.githubusercontent.com/2018660/131864176-f99989c7-167a-473b-b358-bb4ac84e775c.png)

Yours seems to cut off at `function` and is replaced with `f};`.

I don't have any plausible explanations right now, I'll have to think about it. Maybe you have some middlewares that only run in production?

**Comment by antoniodisanto92** [comment]
No. The only difference is that the "dev" (we can call it staging) environment has the APP_ENV=development and use some different environment variables. Nothing more. I will check on nginx too.

**Comment by Tarpsvo** [comment]
That's really weird. I can't reproduce this either. I think it's something specific to your setup.
