### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by jkuzmadx** [optimistdigital/nova-multiselect-field#118]
Hi @Tarpsvo,

Just want to say up front very cool package!

I been testing around with your package for a project of mine and I believe it could be a good candidate. While testing with it I believe I found a bug that I would like to bring to your attention. When I create a new record within the database using Nova I receive the following error message "Array to string conversion" (Screenshot One and Screenshot Two). What makes this interesting is if the record is already exists within the database and I edit it using Nova the error message will not be thrown. After that everything works properly and stores as a string properly within the database. Based on the error message I am seeing I believe it has something to do with the array it self or the searching mechanism. Below you can my code that I am using within my Nova resource if it will be any guidance. I am using additional parameters besides "options" and if you remove everything else the error still throws.

**Screenshot One:**
<img width="934" alt="Screen Shot 2021-08-16 at 1 15 17 PM" src="https://user-images.githubusercontent.com/59975746/129603212-fb2d2f8f-5b3d-443e-993b-e86411ee4a7a.png">

**Screenshot Two:**
<img width="933" alt="Screen Shot 2021-08-16 at 1 33 01 PM" src="https://user-images.githubusercontent.com/59975746/129605394-65b44376-446a-4355-bc71-4385d1bdd02e.png">

**Code:**
[Code.zip](https://github.com/optimistdigital/nova-multiselect-field/files/6994310/Code.zip)

I look forward to hearing from you.

Best Regards,
John Kuzma

**Comment by Tarpsvo** [comment]
Hi @jkuzmadx! I apologize for my slow response. I maintain a lot of packages and have a lot of projects to keep up with at work as well.

Did you manage to solve this issue? My initial thought is that you might not have `$casts = ['simple_form_builder' => 'array']` cast in your model.
