### ISSUE TITLE
Values not filled via ->api()

### ISSUE THREAD

**Issue by reense** [optimistdigital/nova-multiselect-field#119]
Hello,

I'm retrieving values using the ->api() call, which works as expected. The values show up in the multiselect. However, when i save the resource, the field is empty. The values has been synced to the database however. Can someone tell me how. I can get the filled-in values with the ->api() call? This is the call I'm doing:
```

            Multiselect::make('excludable_tickets')
                ->api('/api/multiselect/tickets', Worklog::class),
```

Best regards,

Reense

**Comment by Tarpsvo** [comment]
Hi @reense!

I ran a quick test and it seemed to work as expected.

Is your API endpoint returning the ID-s of Worklog class?

I tested a simple example like this:
```php
Multiselect::make('Users', 'email')
  ->api('/nova-api/users', User::class),
```

And it worked as intended.

Behind the scenes, the values are resolved like this:
```php
$modelObj = $resourceClass::newModel();
$models = $modelObj::whereIn($modelObj->getKeyName(), $value)->get();

// Where $value is the [1,2,3] array of ID-s.
```

Also, are you maybe overriding `->resolveUsing()`? That might cause this issue as well.

**Comment by reense** [comment]
@Tarpsvo 
I'm so sorry for not replying! You were right, I made a mistake in my controller; I did not return the correct entity identifier as key. This issue is resolved. Thank you! :)
