### ISSUE TITLE
Is there a way to set the cast of values saved?

### ISSUE THREAD

**Issue by alekmlynek** [optimistdigital/nova-multiselect-field#122]
I'm using this in conjunction with another module to save categories. The selection keys are numbers, while labels are string.

1=>"Category1"
2=>"Category2"

When I save this in a JSON column, the result is: ["1","2"] not [1,2]

This matters when using DB builder with whereJsonContains. The comparison values are an array of integers, while the database contains an array of strings and the whereJsonContains fails.

Right now, my solution is to cast the integer array as strings, to match what is in the DB, but this isn't elegant. Would much rather just save as integers into the DB from the get-go. Then IDs could be integers everywhere without having to worry about these special cases.

Thank you

**Comment by puremana** [comment]
I'm having the same issue, and not sure how I would use `fillUsing` to solve this

**Comment by KasparRosin** [comment]
@puremana 
You can create a custom cast that parses string to ints.
doc: https://laravel.com/docs/9.x/eloquent-mutators#custom-casts
