### ISSUE TITLE
trait AssociatableRelation not found!

### ISSUE THREAD

**Issue by Shemaees** [optimistdigital/nova-multiselect-field#124]
![a885dc8d-992d-43cd-8cd2-3fa99dad1d52](https://user-images.githubusercontent.com/53188646/136022684-46d360fc-4efc-4559-8b9d-aa25ced926e7.png)
![image](https://user-images.githubusercontent.com/53188646/136022920-869ed288-9895-49a0-a817-d98245736d4f.png)

**Comment by Shemaees** [comment]
its nova 3

**Comment by Tarpsvo** [comment]
Hmm, it seems the trait was a result of a refactor in Nova 3.26 released in June.

I'll see if I can make it backwards compatible.

**Comment by Shemaees** [comment]
thank u so much for this quickly support!
by the way this is an awesome  package. great job and thank u again

**Comment by Tarpsvo** [comment]
This should now be fixed in version 3.2.7. :) Just run composer update. Thanks for reporting this and good luck!
