### ISSUE TITLE
Default selected values 

### ISSUE THREAD

**Issue by lemattou** [optimistdigital/nova-multiselect-field#126]
Hi ! 

I use this multiselect field in Action,
But i didn't find a way to populate value pre-selected 

Can you help me please

**Comment by Tarpsvo** [comment]
```
Multiselect::make('Category')
                ->options([1 => 'one', 2 => 'two'])
                ->default(1);
```

Inside an Action works on my machine.

**Comment by lugamb1** [comment]
I try this examples but i not works for me :(

**Comment by Tarpsvo** [comment]
The default values are only prefilled when creating a new resource. Are you sure you're not updating one?
