### ISSUE TITLE
MultiselectBelongsToSupport importing inexistent class

### ISSUE THREAD

**Issue by troyquides-cp** [optimistdigital/nova-multiselect-field#129]
I'm getting `Class 'Laravel\Nova\Util' not found` error after I upgraded from v2.3.3 to v2.3.11. The class is being imported in the trait `MultiselectBelongsToSupport`, I checked the supposed class base on it's namespace and it doesn't exist in Laravel Nova's vendor directory.

I'm using these atm:
Laravel Nova: v3.22.0
Laravel Framework: 8.67.0

**Comment by Tarpsvo** [comment]
Hi! Apparently \Laravel\Nova\Util was added in version 3.25. I added support for older versions in the new 2.3.12 release.

Thanks for reporting this!
