### ISSUE TITLE
Composer require not working

### ISSUE THREAD

**Issue by InvokerMaster** [optimistdigital/nova-multiselect-field#13]
```
In Nova.php line 706:
                                       
  Method Translations does not exist.
```
When I try to install the package, I got this error while `@php artisan package:discover --ansi`
Would you please take care of this and help me what's wrong?

**Comment by Tarpsvo** [comment]
Hey! It was a typo on my side. I accidentally called `Nova::Translations` instead of `Nova::translations`. As I develop on MacOS and it is case insensitive, it worked on my machine. Anyhow, it was my bad and I fixed it in release 1.3.2. Thanks!
