### ISSUE TITLE
Argument 1 passed to OptimistDigital\MultiselectField\Multiselect::setOptionsFromModels() must be an instance of Illuminate\Support\Collection, null given

### ISSUE THREAD

**Issue by brnteka** [optimistdigital/nova-multiselect-field#131]
`Argument 1 passed to OptimistDigital\MultiselectField\Multiselect::setOptionsFromModels() must be an instance of Illuminate\Support\Collection, null given, called in \vendor\optimistdigital\nova-multiselect-field\src\Traits\MultiselectBelongsToSupport.php on line 102`

Hi and thank you for the package, but ran into this error while trying to add a model and am not sure what I'm doing wrong here. The model is working fine in other parts of code not related to multiselect 

```
Panel::make('Files', [
    Multiselect::make('Files', 'files')->saveAsJSON()->belongsToMany(\App\Nova\File::class)
]),
```

**Comment by Tarpsvo** [comment]
Hi! It seems that your 'files' relationship is invalid or does not exist.

Please make sure your model has a relationship similar to this one:

```php
function files() {
  return $this->belongsToMany(File::class);
}
```
