### ISSUE TITLE
Option to show options without searching

### ISSUE THREAD

**Issue by StanMenten99** [optimistdigital/nova-multiselect-field#132]
Hi,

I would like to see an option where you can show the same select without searching them in particular.
Now I need to press the space key, but for new people using the system this can be confusing and inconvenient.

Is this possible?

PS: Everything is looking good so far!

**Comment by Tarpsvo** [comment]
Yeah, you can disable `$async` for belongsTo/belongsToMany fields by passing `false` as the second argument.

Ie:
```
Multiselect::make('Wat', 'wat')->belongsToMany(Post::class, false),
```
