### ISSUE TITLE
the option value apear as '-' in the dropdown

### ISSUE THREAD

**Issue by khawala** [optimistdigital/nova-multiselect-field#135]
hello i use multiselect to chose multi product 
but in the dropdown menu the value of the product appear as "-" instead of the title of the product 
i don't know why 
![image](https://user-images.githubusercontent.com/43215372/152361244-af6de2a3-4305-41a1-b306-ee005a59ba04.png)

here is how i connect it in the nova resource 
  Multiselect::make('products')
          ->asyncResource(\App\Nova\Product::class)
        ->reorderable(),

the name of the product appear in the edit or view only like that
![image](https://user-images.githubusercontent.com/43215372/152361004-0009961e-85ee-43f7-ab19-be142b3196bd.png)

**Comment by Tarpsvo** [comment]
What version of Nova are you using?

**Comment by khawala** [comment]
> using

![image](https://user-images.githubusercontent.com/43215372/152385059-098b080c-cf7b-4375-ada3-d9cb79806320.png)
it's here sir
