### ISSUE TITLE
belongsToMany with asynchronous option querying: 404 Not Found

### ISSUE THREAD

**Issue by masetto** [optimistdigital/nova-multiselect-field#139]
Hello,
I added Multiselect with "belongsToMany" for asynchronous option querying like this:

```
Multiselect::make('Agreements', 'operator_agreements')
    ->belongsToMany(Agreement::class),
```
When I edit the resource and perform a search I have "404 NOT FOUND" for this get route: `/nova-api/administrators/associatable/operator_agreements?search=fc`

If I set the second argument to 'false' I have no problems.

I don't know if this is an issue or I'm forgetting something.

Thanks

**Comment by Tarpsvo** [comment]
Are you sure that relationship exists on the Administrators model?
