### ISSUE TITLE
Issue Mehotd Translations does not exist

### ISSUE THREAD

**Issue by leodesignDukstra** [optimistdigital/nova-multiselect-field#14]
i installed 1.1 few weeks ago , and it was working fine.
Yesterday i deed composer update and it updated to version 1.3.2 but nova stoped working with the following error.

`BadMethodCallException
Method translations does not exist`

until i had to remove the pakcage then my laravel nova started to work again.

kind you please look into fixing it... ?

**Comment by Tarpsvo** [comment]
What's your Laravel Nova version?

**Comment by leodesignDukstra** [comment]
my current nova version is:
using tinker:

Psy Shell v0.9.9 (PHP 7.2.19-0ubuntu0.18.04.2 — cli) by Justin Hileman
>>> Laravel\Nova\Nova::version();
=> "2.0.0"
>>>

**Comment by Tarpsvo** [comment]
Yeah, the issue with that is that I made the package translatable (all the strings come from a translations file), but Nova added translatable Fields/Tools option in version 2.0.11. Can you update your Nova version to 2.0.11 or later?
