### ISSUE TITLE
When no value is selected with `belongsToMany`, the fill method receives an empty string and cannot sync the relation

### ISSUE THREAD

**Issue by crezra** [optimistdigital/nova-multiselect-field#142]
Hi,

When using `belongsToMany` with a related resource, it happens that the value which gets passed to the field when trying to fill the relationship is an empty string when no related resource is selected.

Steps to reproduce :

1. Have two resources for which the models are related by a belongsToMany relationship
2. Add the `belongsToMany(Resource::class)` method to the field
3. Trying saving the form without filling the input
4. the value that gets passed to the `fillUsing` method is an empty string and fails this check `$relation->sync($request->get($attribute) ?? []);
`

**Comment by Tarpsvo** [comment]
It's now released in version 2.4.0 and will be released in 3.0 as well for Nova 4. Thanks!
