### ISSUE TITLE
Update to Laravel Nova 4 please

### ISSUE THREAD

**Issue by stonkeep** [optimistdigital/nova-multiselect-field#146]
Could please, update to Laravel Nova 4?

**Comment by Tarpsvo** [comment]
Nova 4 support added in version 3.

**Comment by equinoxmatt** [comment]
@Tarpsvo  - why did you drop nova 3 support? Nova 3 supports Laravel 9, but there isn't a version of this package available for Laravel 9 & Nova 3?

If Nova supports it, why not this package?

**Comment by Tarpsvo** [comment]
V3 supports Laravel 9.
