### ISSUE TITLE
Doesn't work as pivot field

### ISSUE THREAD

**Issue by SebastianSchoeps** [optimistdigital/nova-multiselect-field#17]
Thanks for this tool!

When using it as a pivot field in a BelongsToMany relation, the values are stored correctly - but unfortunately not shown in the index or detail view after saving.

Best,
Sebastian

**Comment by pzmarzly** [comment]
I managed to get it working:

```php
// Nova/Task.php: fields()
Multiselect::make(__('Users'), 'users_json')
    ->options(User::all()->map->name),

// Models/Task.php
public function users()
{
    return $this->belongsToMany(User::class);
}

public function getUsersJsonAttribute()
{
    return $this->users->pluck('id')->toJson();
}

public function setUsersJsonAttribute($users)
{
    $this->users()->sync(json_decode($users));
}
```

**Comment by Tarpsvo** [comment]
Hi! Does seem to work for me as a pivot field. Are you sure you included the custom field in the `withPivot` statement?

```
class Artist extends Model
{
    public function tracks()
    {
        return $this->belongsToMany(Track::class)
            ->using(ArtistTrack::class)
            ->withPivot('multiselect_something');
    }
}
```

What @pzmarzly seems to be describing is a way to use Multiselect as a `BelongsToMany` field. This support was added recently.
