### ISSUE TITLE
css class conflict

### ISSUE THREAD

**Issue by kamilkozak** [optimistdigital/nova-multiselect-field#23]
There is a css class conflict between this package and another popular package: https://github.com/whitecube/nova-flexible-content.  Because of this, multiselect does not display the drop down list.

**Comment by alejandrosanchez18** [comment]
Have the same problem, I'm using nova flexible content package too and multiselect not display the drop down list

**Comment by Tarpsvo** [comment]
Hmm, I use the multiselect inside a `Flexible` field and have no issues. Can you please elaborate what CSS class is conflicting?

**Comment by Tarpsvo** [comment]
Still unable to reproduce this. I added a simple Flexible to the default User model and it seems to work fine.

```
Flexible::make('Test')
    ->addLayout('Bleh', 'blah', [
        Multiselect::make('test')
            ->options([
                'en' => 'Test',
                'sv' => 'Tast',
            ]),
    ]),
```

![image](https://user-images.githubusercontent.com/2018660/73169571-043d7580-4105-11ea-8281-f1213410d64b.png)

Please do elaborate further, thanks!

**Comment by kamilkozak** [comment]
Which version of nova-flexible-content are you using? The error occurs on the latest V0.1.13. There is no problem on V0.1.12.

**Comment by Tarpsvo** [comment]
Ah yeah, seems I had fixed the flexible content version to 0.1.12. I now managed to successfully reproduce the issue. Thanks!

The cause of the issue is on the `nova-flexible-content` side. They overwrite the `vue-multiselect` package styles globally (though it should definitely be scoped). I created a PR in their repo and hope it gets merged soon ([nova-flexible-content PR #139](https://github.com/whitecube/nova-flexible-content/pull/139)).

**Comment by kamilkozak** [comment]
Thank you and appreciate it.

**Comment by Tarpsvo** [comment]
@kamilkozak @alejandrosanchez18 `nova-flexible-content` has a new release now, version `0.1.14` that fixes the issue. Good luck!

**Comment by Tarpsvo** [comment]
Scratch that, use version 0.1.15.

**Comment by cloudstudio** [comment]
Hello @Tarpsvo  

I try multiselect with nova-flexible-content, just nothing happend when use dependsOnOptions, something i can look at? thanks for all!

![Captura de pantalla 2020-06-22 a las 13 44 25](https://user-images.githubusercontent.com/3589377/85283929-83559080-b48e-11ea-8ffc-1ac9d6924b84.png)
