### ISSUE TITLE
Save multi-selected values as native array

### ISSUE THREAD

**Issue by hasnatbabur** [optimistdigital/nova-multiselect-field#26]
Can we save multi-selected values as native array in database? Because most of the time we will use casting in Model with array conversion. Adding quote ("") around the values triggers error while looping.

Thanks

**Comment by Tarpsvo** [comment]
Hey! Did you try the `->saveAsJSON()` option?

**Comment by hasnatbabur** [comment]
@Tarpsvo Thanks, it worked like a charm!
