### ISSUE TITLE
Feature Request - valueAsHtml() for options value

### ISSUE THREAD

**Issue by Equruler** [optimistdigital/nova-multiselect-field#27]
I would like to have a feature request - valueAsHtml()

I hope there will be a method like valueAsHtml() to let me inject some HTML to the value.
So that I can make some image or link elements to the value, then user can select/view our values with thumbnail.
I hope I can doing this with a simple injecting value method instead of overriding the vue.

Appreciate if there will be a option to let {{ value }} become {!! value !!}

This package is great!

**Comment by Tarpsvo** [comment]
Hi! Unfortunately this can't be done as easily as just echoing ` {!! value !!}`. This package uses vue-multiselect and overwriting the option template isn't as straightforward as it seems.

See the docs: https://vue-multiselect.js.org/#sub-custom-option-template

I think it would be easier for you to create a custom Select for that usecase.

**Comment by vesper8** [comment]
I was able to achieve this by overriding the form tag and form option components inside of a new Nova asset

```

import FormFieldTag from "./components/FormFieldTag";
import FormFieldOption from "./components/FormFieldOption";
// import NovaMultiselectDetailFieldValue from './components/NovaMultiselectDetailFieldValue';

Nova.booting((app, store) => {
    app.component("form-multiselect-field-tag", FormFieldTag);
    app.component("form-multiselect-field-option", FormFieldOption);
    // app.component('nova-multiselect-detail-field-value', NovaMultiselectDetailFieldValue);
});
```

Then inside my options I return json instead of just the label, and in my override components I can then display whatever html I want inside the select options and selected tags
