### ISSUE TITLE
Items count won't display on index

### ISSUE THREAD

**Issue by J0hnnyDaniel** [optimistdigital/nova-multiselect-field#3]
Items count won't display on index, instead it's just a blank column.

**Comment by Tarpsvo** [comment]
Hi, can you specify whether it is completely empty or does it show a `-` when null?

**Comment by J0hnnyDaniel** [comment]
Hello, its completely empty

**Comment by J0hnnyDaniel** [comment]
Also, if I may, i would suggest an option to show the labels of the selected options as "Item1, Item2, Item3, ..." on index. It would be quite useful.

**Comment by Tarpsvo** [comment]
It does actually. Unless the char count exceeds 40. See [IndexField.vue](https://github.com/optimistdigital/nova-multiselect-field/blob/master/resources/js/components/IndexField.vue)

**Comment by Tarpsvo** [comment]
I'm still unable to reproduce the issue you're having. Can you show what's stored in the database?

**Comment by J0hnnyDaniel** [comment]
Sorry for the long delay, I'm not at the office right now but, the options were something like [ 1=> 'home', 2=>'office'], and it would save in the DB like [1,2]

**Comment by J0hnnyDaniel** [comment]
Also, the item could would be completely empty

**Comment by smartens80** [comment]
I am having the same issue. What was the resolution?

**Comment by Tarpsvo** [comment]
I tested it on my local and I think I was able to reproduce it. I released a fix for it in version 1.3.4.
