### ISSUE TITLE
null as string

### ISSUE THREAD

**Issue by kamilkozak** [optimistdigital/nova-multiselect-field#30]
An empty value is stored as a "null" string. Regardless of the nullable () method

**Comment by Tarpsvo** [comment]
Hi! I wasn't able to reproduce this issue. Can you copy the code where you create the Multiselect field?

**Comment by KangYoosam** [comment]
@kamilkozak 
I faced same problem, but it resolved when I use `saveAsJSON()` method.
hope it helps you.

**Comment by mstyles** [comment]
Ran into this issue as well, using the latest version (1.9.0). I've submitted a fix here: https://github.com/optimistdigital/nova-multiselect-field/pull/48
