### ISSUE TITLE
Options Group: Visual 

### ISSUE THREAD

**Issue by cord** [optimistdigital/nova-multiselect-field#33]
Great package!
Currently the Option Groups are helpful for selecting values, but afterwards it is not possible to distinguish them:
![edit?viaResource= viaResourceId= viaRelationship= 2020-03-25 12-22-13](https://user-images.githubusercontent.com/158588/77531622-817e3000-6e93-11ea-840b-71a6fb330a56.png)

Would be great to have visual support for the selected options.

**Comment by Tarpsvo** [comment]
Hi! Thanks for reporting this and sorry for the late action. The multi-select will now display the group in brackets behind the option label if multiple options have the same label in different groups. Good luck!
