### ISSUE TITLE
saveAsJson()

### ISSUE THREAD

**Issue by latwelve** [optimistdigital/nova-multiselect-field#35]
Hey thanks for the package

I'm using the latest version of nova 3.3.2 and saveAsJson() is not working how I had expected for a json column.

expected to see {"example_1","example_2} but I get  ["example_1","example_2]

Is this expected behaviour?

Also can you please expand on the documentation for "Overwriting the detail field" I have no idea if that should be a new nova-component or within base resources or nova/resources

I've tried the latter 2 but couldn't get it to overwrite so I'm guessing it maybe a nova-component but when setting up a nova-component it usually wants vendor/package not just package?

**Comment by alberto-bottarini** [comment]
I think it's right. Arrays in JSON are represented using square brackets

**Comment by latwelve** [comment]
> I think it's right. Arrays in JSON are represented using square brackets

ah thanks for confirming, it's just I was used to other fields wrapping with curly brackets but I guess it makes sense in this case as its only 1 list of values.

I don't suppose you can help with my second question in my original post?

Thanks again

**Comment by alberto-bottarini** [comment]
I've never used that feature, I'm sorry
