### ISSUE TITLE
Stored value not prefilled when updating resource

### ISSUE THREAD

**Issue by mattyh88** [optimistdigital/nova-multiselect-field#36]
Hi, 

I have the MultiSelect field setup as followed: 

    $options = $optionRepository->selectAll()
        ->pluck('name', 'id');

    MultiSelect::make('Options')
        ->options($options->toArray())
        ->onlyOnForms(),

This works brilliantly for the create form (values are stored in DB), but it's not prefilling my field in the edit form. 
When I check the ajax call, to get the Resource's fields for the edit form, I can see that the MultiSelect field has the correct values. It's just not setting the div element with class multiselect__tags.

Nova version: 2.12.0
optimistdigital/nova-multiselect-field: 1.9.0

Thanking you in advance.

**Comment by Tarpsvo** [comment]
That's really weird. I set up a new Nova project with Nova 2.12.0 and Nova Multiselect 1.9.0 and it worked as intended.

```php
Multiselect::make('Multiselect')
  ->options([1 => 'Haha', 2 => 'Hehe', 3 => 'Huhu'])
  ->onlyOnForms(),
```

Tried with both numeric and string keys. Not sure what's wrong to be honest. Maybe try running `php artisan nova:publish` and `composer update` again? :S

**Comment by mattyh88** [comment]
The only custom thing I did have to do, is feed my Multiselect field, through an Observer (via the retrieved event model). I needed to do this because I want to store values for a many to many relation: A **plan** has many **options** and an **option** has many **plans**.

    public function retrieved(Plan $plan)
    {
        $optionIds = $plan->options
            ->pluck('name', 'id');

        $attributes = $plan->getAttributes();
        $attributes['options'] = json_encode($optionIds);
        $plan->setRawAttributes($attributes);
    }

**Comment by mattyh88** [comment]
Issue solved. Was storing the values in the database in an incorrect way ("id":"value" in JSON format). I was manipulating these values manually, because of my many-to-many relation.
