### ISSUE TITLE
Overwriting the detail field: Expand docs for a noobie?!

### ISSUE THREAD

**Issue by latwelve** [optimistdigital/nova-multiselect-field#38]
Hi I don't understand the docs fully, I've tried make:component but I think its wrong do I need to create a nova-tool to overwrite the styling via the instructions in your docs?

Please can you elaborate on them a little more so they are a little more beginner friendly

Thanks for the package

**Comment by Tarpsvo** [comment]
I believe the example given is sufficient. Create a NovaMultiselectDetailFieldValue.vue file in your project and register it in your project's `resources/app.js` and it will overwrite the component that comes default with this package.

**Comment by latwelve** [comment]
> I believe the example given is sufficient. Create a NovaMultiselectDetailFieldValue.vue file in your project and register it in your project's `resources/app.js` and it will overwrite the component that comes default with this package.

I appreciate that it's obvious to someone that knows but honestly I don't have a clue where it registers.. I tried the main laravel resources > js > app.js  and also placed the vue file in this folder and ran npm run watch and saw it was compiled in but it didnt display any differently (I set all classes to blank in the vue file just to see).

Then I realised it may need to be loaded in the /nova directory (I'm using the zip install) 

So I've tried /nova/resources/js/app.js  and placed the vue file here too.. I then took dist off the webpack js as I've have no need to run npm install and npm run production in this folder yet as I assumed it was reserved for just core files... again it's still not worked but I can see my includes are in the exported files....

So I really don't know what I'm doing wrong which is why I've asked for a bit more clarity please!

Thanks
Alex

**Comment by dillingham** [comment]
@latwelve if you register a component within app.js.. its not going to be seen by Nova.

The vue instance in resources/js/app.js isn't loaded on the page. 

If you run `php artisan nova:asset latwelve/whatever` it will spit out a js file that will be seen by nova.

If you want full access to nova's vue instance, router or store you can use:

```
Nova.booting((Vue, router, store) => {
    Vue.component(...);
});
```

**Comment by frosass** [comment]
That would be awesome. I couldn't override it. I've tried a lot without success. Can someone, please, help me?
