### ISSUE TITLE
[FEATURE REQUEST ]Order group options

### ISSUE THREAD

**Issue by skoyah** [optimistdigital/nova-multiselect-field#39]
Hi there! Great package!

Would be nice if we could define if the groups could be ordered by asc/desc order.

Do you think this could be a nice improvement to the package?

**Comment by Tarpsvo** [comment]
Hi! Can you elaborate? What's stopping you from ordering the options in your resource?

**Comment by skoyah** [comment]
You are right, I have to order them before passing them as a prop.
