### ISSUE TITLE
dependsOnOptions compatibility with nova-flexible-content

### ISSUE THREAD

**Issue by cloudstudio** [optimistdigital/nova-multiselect-field#42]
Hello @Tarpsvo 

I try multiselect with nova-flexible-content, just nothing happend when use dependsOnOptions, something i can look at? thanks for all!

Maybe it has something to do with the field index?

![Captura de pantalla 2020-06-22 a las 13 44 25](https://user-images.githubusercontent.com/3589377/85290408-3d51fa00-b499-11ea-8698-7b698357b570.png)

**Comment by Tarpsvo** [comment]
Hi! I added compatibility for dependsOn and Flexible in version 1.9.6. Check it out! Good luck!
