### ISSUE TITLE
Default values 

### ISSUE THREAD

**Issue by JoseLuisRNP** [optimistdigital/nova-multiselect-field#43]
I'm trying to set some default values but i dont' get it.

Example: 
```
Multiselect::make('tag')->options([
    1 => 'First',
    2 => 'Second',
    3 => 'Third',
])

```
`->default()`  method see like doesn't exist in Multiselect
`->withMeta(['value' => [1, 2]) ` i work around withMeta without success.

Some help with it? I looking in closed issues like #37 and #22

**Comment by Tarpsvo** [comment]
Did you test `->default()`. Multiselect extends the Nova Field class, so it definitely has `->default()`.

**Comment by JoseLuisRNP** [comment]
See like default not implemented in my version of Nova in this proyect, i look in another with the last Nova version and it is.  In any case `->default()` seem doesn't work.

I've managed to make it work with `->withMeta(['value' => [[1], [2]])` finally. Maybe is goo idea put a example at the readme, if you doesn't have time and accept PR i will do it. 

Thanks for this great package
