### ISSUE TITLE
Eager Loading is not used and each query is duplicated

### ISSUE THREAD

**Issue by aghayeff** [optimistdigital/nova-multiselect-field#44]
**tags (categories) for each row is displayed with a query, without an eager loading and each query is also duplicated.** 

I added relationship name into `with` array in resource, but nothing is changed. It is tested using `belongsToMany` relationship.

            Multiselect
                ::make(__('Categories'), 'categories')
                ->options([1 => 'bla', 2 => 'bla bla'])
                ->rules('required'),

Please take a look to attached file, for more info.

2 rows, 4 belonged queries:

<img width="892" alt="Screen Shot 2020-07-15 at 00 19 23" src="https://user-images.githubusercontent.com/7493431/87472705-6c3f3400-c631-11ea-878d-f2ca5179d6a9.png">

**Comment by Tarpsvo** [comment]
Hi!

Isn't caching the relationship results something you should handle? Your example doesn't really provide a good insight either.

For example:

```
// Instead of
Multiselect::make(__('Categories'), 'categories')
  ->options(Category::all()->pluck('name', 'id')->toArray())
  ->rules('required'),

// You could do:
class SomeResource extends Resource {
  protected $cachedCategories = null;

  public function fields() {
    if (!$cachedCategories) $cachedCategories = Category::all()->pluck('name', 'id')->toArray();

    return [
      Multiselect::make(__('Categories'), 'categories')
        ->options($cachedCategories)
        ->rules('required'),
    ];
  }
}
```

I don't see any plausible way I could cache the options between the resources inside this package.

**Comment by aghayeff** [comment]
with options there is not any problem, if you cache it. You can easily see, how the query is duplicated from screenshot.
 Forget about options okay? It will be happened even, if you remove options line.

Duplicating is regarded with relationship (categories)

    public function categories()
    {
        return $this->belongsToMany(Page::class, 'product_categories');
    }

**Comment by Tarpsvo** [comment]
I don't understand how this is related to Multiselect right now. Can you provide a more complete example?

**Comment by aghayeff** [comment]
Take a look to this line:

`Multiselect::make(__('Categories'), 'categories')`

So, `categories` is a name of a field and also is a name of relationship. Right?
If you rename categories to category, displaying tags will not work in index and detail page.

But, this `categories` relationship is called every time.  For example, if you have 25 rows in index page, categories relationship will be called 25 times...

```
public function categories()
{
    return $this->belongsToMany(Page::class, 'product_categories');
}
```

**Comment by aghayeff** [comment]
Sorry, it was my mistake. I used mutators and it had been crated duplicated queries,
