### ISSUE TITLE
Null values being saved as 'null' string

### ISSUE THREAD

**Issue by mstyles** [optimistdigital/nova-multiselect-field#49]
For nullable fields which do not saveAsJSON, if the value is null it was being encoded and turned into a 'null' string. I am using the latest version (1.9.0). This issue was reported previously but was closed (https://github.com/optimistdigital/nova-multiselect-field/issues/30), so I'm recreating it (feel free to close this one if we don't want a duplicate). I've submitted a fix here: https://github.com/optimistdigital/nova-multiselect-field/pull/48

_Originally posted by @mstyles in https://github.com/optimistdigital/nova-multiselect-field/issues/30#issuecomment-661249731_

**Comment by Tarpsvo** [comment]
Thanks a lot! I merged your PR and released it in version 1.9.1. Good luck!

**Comment by mstyles** [comment]
Wow, thanks for such a quick response and new release! I appreciate it 🥰
