### ISSUE TITLE
Multiselect open without clicking on it

### ISSUE THREAD

**Issue by Mihai-github** [optimistdigital/nova-multiselect-field#50]
Hi, 
    Is there a way to stop the multiselect from opening itself without me click on it? Probably have something with the css class but I'm not sure how can i make the changes and some help would be greate

**Comment by Tarpsvo** [comment]
Can you confirm this issue still persists? I can not reproduce this.

**Comment by latwelve** [comment]
It opens without input for me on an action $field using:

`            Multiselect::make('Availabilities', 'availabilities')
                ->options(
                    $availabilities
                )
                ->saveAsJSON()
                ->placeholder('Select additional availabilities'),
`

**Comment by Tarpsvo** [comment]
In Actions, Nova automatically focuses the first field.

You can add a `Hidden::make()` field as the first field if you want to work around this.
