### ISSUE TITLE
'e.toUppercase is not a function'

### ISSUE THREAD

**Issue by Paulsky** [optimistdigital/nova-multiselect-field#51]
Hello,

Since 1.9.1 I'm getting 'e.toUppercase is not a function', even though there is no MultiSelect field rendered on the current page.

**Comment by Paulsky** [comment]
Sorry, apparently I was wrong and it was another package responsible for this.

**Comment by Tarpsvo** [comment]
Hi! This issue is indeed caused by Nova Multiselect in Nova 3.8.0 and later, but it's an issue in Nova's code and I'm waiting for them to accept a PR and release it. Thanks!
