### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.toUpperCase')

### ISSUE THREAD

**Issue by ibrunotome** [optimistdigital/nova-multiselect-field#52]
This error appears from Nova v3.8.0 and above. I'm using 1.9.1 of this package.

**Comment by steveallinson** [comment]
Can confirm the same error on the latest version of multiselect and Nova. Appears to be broken on all our up to date projects.

**Comment by Tarpsvo** [comment]
Hi!

This is an issue with Laravel Nova and will be resolved shortly, after the PR at https://github.com/laravel/nova/pull/931 is merged.

Let us wait for them to act.

**Comment by Tarpsvo** [comment]
Seems like they pushed the buggy release and all went on vacation. I added a fix to this package and released it in version 1.9.2.
