### ISSUE TITLE
Does not work on update view on latest Nova version (3.8.2)

### ISSUE THREAD

**Issue by phlisg** [optimistdigital/nova-multiselect-field#53]
Hello!

I am using version 1.9.1 of this package in the context of Nova v3.8.2.

All Multiselect fields I have don't render at all on the update screen. They do show up correctly in the details view though, but it makes me unable to create new resources with required `Multiselect` fields.

Example implementation:

```php
Multiselect::make("Langues", 'languages')
    ->options(Languages::all())
    ->reorderable()
    ->saveAsJSON()
    ->placeholder('Définir les langues pour cet objet.')
    ->help("Définir les langues pour cet objet.")
    ->hideFromIndex()
    ->rules('required')
    ->updateRules('sometimes')
    ->displayUsing(function ($value) {
        if (is_array($value)) return json_encode($value);
        return $value;
    });
```

I'm not too sure why this is happening. I get errors in the JS console but they are related to another package (flexible content).

**Comment by Tarpsvo** [comment]
Nova 3.8.0 introduced a pretty big bug that causes crashes into the translation mechanism. You can revert to Nova 3.7.X for now or wait for 3.8.3 with the fix. The PR is still open though. See #52

**Comment by phlisg** [comment]
Oh, thank you for the heads up. I did not see #52 before posting this, sorry for the disturbance. Thank you for the prompt answer!
