### ISSUE TITLE
Not Working with eminiarts/nova-tabs TabsOnEdit

### ISSUE THREAD

**Issue by DerekBuntin** [optimistdigital/nova-multiselect-field#56]
I tried loading the field on a tab within eminiarts/nova-tabs using TabsOnEdit but the field doesn't load.

Console displayed `TypeError: e.toUpperCase is not a function`

**Comment by Tarpsvo** [comment]
Hi! This is a Nova 3.8.0-3.8.2 issue. Please upgrade to Nova Multiselect version 1.9.2 (or downgrade Nova to 3.7.0).

**Comment by DerekBuntin** [comment]
> Hi! This is a Nova 3.8.0-3.8.2 issue. Please upgrade to Nova Multiselect version 1.9.2 (or downgrade Nova to 3.7.0).

I currently use Nova 3.8.2 and Multiselect 1.9.2 and this issue still exists.

I've copied the same code you have on the description but when I go to the nova resource in admin the field doesn't load at all.

`Multiselect
        ::make('Favourite football teams', 'football_teams')
        ->options([
          'liverpool' => 'Liverpool FC',
          'tottenham' => 'Tottenham Hotspur',
          'bvb' => 'Borussia Dortmund',
          'bayern' => 'FC Bayern Munich',
          'barcelona' => 'FC Barcelona',
          'juventus' => 'Juventus FC',
          'psg' => 'Paris Saint-Germain FC',
        ])

        // Optional:
        ->placeholder('Choose football teams') // Placeholder text
        ->max(4) // Maximum number of items the user can choose
        ->saveAsJSON() // Saves value as JSON if the database column is of JSON type
        ->optionsLimit(5) // How many items to display at once
        ->reorderable() // Allows reordering functionality
        ->singleSelect() // If you want a searchable single select field`

**Comment by Tarpsvo** [comment]
Hi!

I released version 1.9.3 with more workarounds for the Nova's translations issue. Please try it out and let me know if it works for you now. Thanks!

**Comment by DerekBuntin** [comment]
> Hi!
> 
> I released version 1.9.3 with more workarounds for the Nova's translations issue. Please try it out and let me know if it works for you now. Thanks!

Perfect it's working @Tarpsvo, great work!
