### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by tousif786** [optimistdigital/nova-multiselect-field#59]
When using in your own nova menu builder as a custom field, the dropdown is totally out. See visibility field in below screenshot.

![Capture](https://user-images.githubusercontent.com/7187324/91104337-fc3bb900-e686-11ea-9d9e-8477b14a4364.JPG)

**Comment by KasparRosin** [comment]
Hey!
This issue came from [nova-menu-builder](https://github.com/optimistdigital/nova-menu-builder). This has been fixed in version [3.0.1](https://github.com/optimistdigital/nova-menu-builder/releases/tag/3.0.1) of nova-menu-builder. 
Thank you for reporting this.
