### ISSUE TITLE
Is there a way to have default options when your are using dependsOn method

### ISSUE THREAD

**Issue by evidencefrank** [optimistdigital/nova-multiselect-field#60]
Hi Guys,
Thank you for this wonderful package. It really is a great one.

I would like to know if its possible to have default options when you're using the dependsOn method.

            `Multiselect::make('Report Year', 'report_year')
                ->options(array_combine(range(date("Y"), 2010), range(date("Y"), 2010)))
                ->singleSelect()
                ->rules('required')
                ->onlyOnForms(),`

            `Multiselect::make('Report Month', 'report_month')
                ->dependsOn('report_year')
                ->dependsOnOptions([
                    date("Y") => $this->months(),
                   ])
                ->default($this->allMonths()). // something like this but its not working
                ->singleSelect()
                ->rules('required'),`

I would like to show only months that have passed in the current Year and then all months for the previous years.
Is this possible?
Thanks.

**Comment by Tarpsvo** [comment]
Hi! I think this would require `->dependsOnDefaults()` or something similar and I think it overcomplicates things a bit. There's no way to do this currently unfortunately and I don't plan on making this either in the near future, sadly. :(
