### ISSUE TITLE
Does not save json in nova menu builder

### ISSUE THREAD

**Issue by tousif786** [optimistdigital/nova-multiselect-field#61]
Here is my code in nova menu builder

```
public static function getFields(): array
    {
        return [
            Multiselect::make('Visibility', 'role')
                ->options(\App\Role::all()->except(1)->pluck('label', 'name')->toArray())
                ->saveAsJSON(true)
        ];
    } 
```
When update menu item it saves `{"data": null, "role": null}` empty json object like this into the data column in nova_menu_menu_items table.

**Comment by Tarpsvo** [comment]
Hi! Sorry about the delay, I was on vacation. However, I fixed it and released it in version 3.0.2. Let me know how it goes, good luck!

**Comment by tousif786** [comment]
Thanks, all good now.

**Comment by mikeanan** [comment]
Hi, @Tarpsvo,

I follow @tousif786's example code and also setsaveAsJson(true),
but I get the result saved as [ "a", "b", "c" ] not like @tousif786's json type:  {"data": null, "role": null}.
Any suggestion?
