### ISSUE TITLE
Enable single-select or multi select based on condition?

### ISSUE THREAD

**Issue by Jun-ocx** [optimistdigital/nova-multiselect-field#62]
Is there a way to implement the function in case where something is "active" ->singleSelect(true) otherwise singleSelect(false)?

EX)
->dependsOn('is_active')
->singleSelect(function () if('is_active' == 1) return true; else return false))

If it is working as dependsOnOptions, it can't be better

Thanks in advance

**Comment by Tarpsvo** [comment]
Hi! I don't think it's good practice to add a feature like that due to the nature of data (multi-select saves an array while singleSelect will save a single value).

However, I did add `dependsOnMax` option where you can specify a max of `1` to limit the max amount of selected options to 1.
