### ISSUE TITLE
Object as key for v-for

### ISSUE THREAD

**Issue by DanielLavoie90** [optimistdigital/nova-multiselect-field#63]
https://github.com/optimistdigital/nova-multiselect-field/blob/14839bd29be3c76fcde35720ea5c9f0500e560ab/resources/js/components/FormField.vue#L49

Can you change that to s.value since the selected values will always be an object with a label and a value at least.

Or use the index in the array.

**Comment by DanielLavoie90** [comment]
v-for="(s, index) in selected" :key="index"

**Comment by Tarpsvo** [comment]
Ah yes, that really is an incorrect key. I fixed it in version 1.9.8. Thanks and good luck!
