### ISSUE TITLE
BelongsToMany does not store order

### ISSUE THREAD

**Issue by jberculo** [optimistdigital/nova-multiselect-field#66]
Hi,

First of all, thanks for the work on this package. 

I've got belongsToMany working, the only thing missing is the order of the items. Changing them after the initial save does not work. Is there a column or something on the pivot table that I should add? Or is this functionality not available for the belongsToMany?

Regards,
Joost.

**Comment by Tarpsvo** [comment]
Hi!

Yeah, it's not possible to properly sort with BelongsToMany cause there's no primary keys and sort order keys on the pivot table. In short, no, reorder is not available for BelongsToMany. Sorry.

Theoretically it might be possible to detach all the items and re-attach them in the new order, but that definitely doesn't guarantee that the order persists.

**Comment by SwenVanZanten** [comment]
Wouldn't it be possible to add the the order in a column in the pivot table? 🤔
