### ISSUE TITLE
using dependsOn with belongsToMany hides the field

### ISSUE THREAD

**Issue by Slgoetz** [optimistdigital/nova-multiselect-field#70]
I am looking to use the `dependsOn` feature with the `belongsToMany` feature.  Essentially we have groups of categories that we want to show depending on another field. Right now if we try to use these two features together nothing shows up. 

```
Multiselect::make('Topics', 'topics')
  ->dependsOn('teachable_type')
  ->dependsOnOptions([
     'activity' => $activity,
     'skill'    => $skill,
     'tls'      => $tls,
  ])
  ->belongsToMany('App\Nova\Category')
  ->hideFromIndex()
  ->nullable(),
```

**Comment by Tarpsvo** [comment]
`->dependsOnOptions` and `->belongsToMany` are both for defining options, they shouldn't be on the same Multiselect instance.

Consider this example:

```
Multiselect::make('Tracks', 'tracks')
    ->belongsToMany(Track::class),

Multiselect::make('Whatever', 'whatever')
    ->dependsOn('tracks')
    ->dependsOnOptions([
        $track1->id => ['it' => 'Italia'],
        $track2->id => ['et' => 'Estonian'],
    ]),
```

Can you explain what you're trying to do? Thanks!

**Comment by farwish** [comment]
Sometimes 'multiselect' need to depends on other fields. for example:

```
BelongsTo::make('Category', 'category'),

Text::make('NAME', 'name'),

Multiselect::make('Whatever', 'whatever')
    ->dependsOn('Category', 'category_id')
```

@Tarpsvo  @Slgoetz

**Comment by Slgoetz** [comment]
Yes, essentially I want to filter down a relationship (Category) based on the the Type of entity.

**Comment by farwish** [comment]
Now i find a solution is BelongsToManyField component from nova community, same style as MultiSelect. @Slgoetz 
Gook luck.
