### ISSUE TITLE
Trying to get property 'id' of non-object on belongsTo

### ISSUE THREAD

**Issue by MB116** [optimistdigital/nova-multiselect-field#74]
Error Trying to get property 'id' of non-object on belongsTo, how it's work?

**Comment by Tarpsvo** [comment]
Hi! Does this still happen with version 1.11.2? If yes, can you paste me your field (how you're creating the Multiselect)? Thanks!

**Comment by Tarpsvo** [comment]
Ah yes - I managed to reproduce it. You forgot to mention it happened on Create view. Fixed in version 1.11.3.
