### ISSUE TITLE
Make asynchronous searching optional

### ISSUE THREAD

**Issue by MJTheOne** [optimistdigital/nova-multiselect-field#75]
I had to downgrade your module to 1.10.* to be able to always show the results.
We are using your module to display a small amount of possibilities to link to a user/resource.
But having to search for them in stead of just showing them is really annoying.
But this also means I cannot use the "belongsTo" in the future because you released that addition together with the asynchronous searching...

Could you please make this an optional feature *or* add in a feature to always show everything?

Thanks

**Comment by Tarpsvo** [comment]
Hi! Added in version 1.11.2, new function signatures are `belongsTo($resourceClass, $async = true)`and `belongsToMany($resourceClass, $async = true)`. Just pass in `false` as second argument. Good luck!
