### ISSUE TITLE
Belons To Not Working

### ISSUE THREAD

**Issue by hananloser** [optimistdigital/nova-multiselect-field#77]
![image](https://user-images.githubusercontent.com/23658759/99966688-a4216980-2dd1-11eb-9f28-8ded116aa2b0.png)

But i Got

![image](https://user-images.githubusercontent.com/23658759/99966741-b8fdfd00-2dd1-11eb-8e31-197c6b25c86d.png)

**Comment by Tarpsvo** [comment]
Can you show me more of the stacktrace please? Which line it occurs at etc.

**Comment by hananloser** [comment]
> Can you show me more of the stacktrace please? Which line it occurs at etc.

`[2020-11-24 17:50:36] local.ERROR: Trying to access array offset on value of type null {"userId":101,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /home/hanan/projects/cerebellum_pendaftaran_online/vendor/optimistdigital/nova-multiselect-field/src/Multiselect.php:318)
[stacktrace]
#0 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/optimistdigital/nova-multiselect-field/src/Multiselect.php(318): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: OptimistDigital\\MultiselectField\\Multiselect->OptimistDigital\\MultiselectField\\{closure}()
#2 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Fields/Field.php(252): call_user_func()
#3 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Laravel\\Nova\\Fields\\Field->Laravel\\Nova\\Fields\\{closure}()
#4 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Fields/Field.php(253): tap()
#5 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Fields/FieldCollection.php(51): Laravel\\Nova\\Fields\\Field->resolve()
#6 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Laravel\\Nova\\Fields\\FieldCollection->Laravel\\Nova\\Fields\\{closure}()
#7 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Fields/FieldCollection.php(53): Illuminate\\Support\\Collection->each()
#8 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/ResolvesFields.php(315): Laravel\\Nova\\Fields\\FieldCollection->resolve()
#9 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/ResolvesFields.php(295): Laravel\\Nova\\Resource->resolveNonPivotFields()
#10 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/eminiarts/nova-tabs/src/TabsOnEdit.php(25): Laravel\\Nova\\Resource->resolveFields()
#11 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/ResolvesFields.php(179): App\\Nova\\Resource->creationFields()
#12 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Http/Controllers/CreationFieldController.php(23): Laravel\\Nova\\Resource->creationFieldsWithinPanels()
#13 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\CreationFieldController->index()
#14 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#15 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Route.php(255): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#16 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#17 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\\Routing\\Route->run()
#18 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#19 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authorize->handle()
#21 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\BootTools->handle()
#23 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Http/Middleware/DispatchServingNovaEvent.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle()
#25 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#27 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#29 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle()
#30 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#32 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\\Pipeline\\Pipeline->then()
#43 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Router.php(668): Illuminate\\Routing\\Router->runRouteWithinStack()
#44 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Router.php(634): Illuminate\\Routing\\Router->runRoute()
#45 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->dispatchToRoute()
#46 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#47 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#48 /home/hanan/projects/cerebellum_pendaftaran_online/nova/src/Http/Middleware/ServeNova.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#50 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#52 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#56 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#58 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(87): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#60 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#62 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#64 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#66 /home/hanan/projects/cerebellum_pendaftaran_online/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#67 /home/hanan/projects/cerebellum_pendaftaran_online/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#68 /home/hanan/.config/composer/vendor/genesisweb/valet-linux-plus/server.php(276): require('/home/hanan/pro...')
#69 {main}
"} 
`

**Comment by Tarpsvo** [comment]
Hi! Added more failsafes, please try out version 1.11.5. Good luck!
