### ISSUE TITLE
grouped Multiselect Field List

### ISSUE THREAD

**Issue by Wissamus** [optimistdigital/nova-multiselect-field#79]
Hello World,
currently i use this package https://packagist.org/packages/optimistdigital/nova-multiselect-field to group a multiselct list but i don't know how to manage the pivot table.

Below my code :
this function ollow us to filter the client rights :

```
  public function clientRights(){

        $clients = DB::table('clients as cli')->select('cli.name as label', 'cli.first_name as lab', 'ent.name as group')
            ->leftJoin('companies as ent', function ($join) {
                $join->on('ent.id', '=', 'cli.company_id');
            })
            ->get();
        $return = [];
        foreach($clients as $client){
            $case = ["label" =>  $client->label.' '.$client->lab, "group" => $client->group];
            array_push($return, $case);
        }
        return $return;

    }
```

I use this Multiselect :

```
Multiselect::make('Users rights', 'clients')->options(function (){
                    return $this->clientRights();
                }
 )->groupSelect(),
```

"culmun clients doesn't exist " so when we try to record our form we have an error telling us that this column does not exist in the table, which is normal.

I want to do something like this { BelongsToManyField::make('Utilisateurs ayant droit', 'clients', 'App\Nova\Client') } but with the Multiselect.

Any suggestion ?

SOS HELP

**Comment by Wissamus** [comment]
https://media.tenor.com/images/c06b7eb4bc20fd87c4e9ee672d8b1c50/tenor.gif

**Comment by Wissamus** [comment]
![image](https://user-images.githubusercontent.com/26502362/102075256-48f9fa00-3e06-11eb-8f67-2e1fb5f477be.png)

**Comment by Tarpsvo** [comment]
You can achieve this using `->fillUsing()` and `->resolveUsing()` callbacks.
