### ISSUE TITLE
e.fill is not a function - most likely due to missing options()

### ISSUE THREAD

**Issue by jonasbrenig** [optimistdigital/nova-multiselect-field#80]
This is just for other people running into the same error.

I just figured out that you get a Javascript error `e.fill is not a function` if you forget to specify the `options()`.
In my case since I am using `asyncResource()` I was not noticing that I needed the options.
For `asyncResource()` you can also use an empty array.

example:

```php
Multiselect::make('Purchase ID', 'purchase_id')
    ->options([])
    ->singleSelect()
    ->rules('required')
    ->asyncResource(Purchase::class)
```

**Comment by Tarpsvo** [comment]
Hi! Should be fixed in 2.0.1. Thanks for reporting this! Good luck!
