### ISSUE TITLE
Not work getFallbackLocale method

### ISSUE THREAD

**Issue by condor-bird** [optimistdigital/nova-multiselect-field#85]
PHP version: 7.4
Laravel version: 7
Nova version: 3.0

```
Error
Call to undefined method Illuminate\Foundation\Application::getFallbackLocale()
```

If you replace:

`$fbLocale = app()->getFallbackLocale();`

on

`$fbLocale = config('app.fallback_locale');`

then it works.

**Comment by Tarpsvo** [comment]
Please upgrade to Laravel 7.21 or later.
