### ISSUE TITLE
Overriding detail field

### ISSUE THREAD

**Issue by frosass** [optimistdigital/nova-multiselect-field#90]
Hi. 
I need some help how to override detail field on the package. Could, please, someone explain to me?

**Comment by KasparRosin** [comment]
https://github.com/optimistdigital/nova-multiselect-field#overwriting-the-detail-field

Here is the documention on how to override detail field.

Make sure include the app.js file inside your NovaServiceProvider/AppServiceProvider, so that it is loaded.
