### ISSUE TITLE
Weird option title behavior

### ISSUE THREAD

**Issue by JeffBeltran** [optimistdigital/nova-multiselect-field#93]
I noticed that options don't work if a resource uses the title method, it only shows the resources id, is there something im missing? or should #89 fix this?

<img width="733" alt="image" src="https://user-images.githubusercontent.com/22965241/113497953-49092d00-94bd-11eb-8e85-3e68ff9000e4.png">

```
Multiselect::make('Agencies')->belongsToMany(Agency::class, false),
```

if i remove that aync param (set or set true), they do show up on creation, but on the views they will still show up as ids

<img width="440" alt="image" src="https://user-images.githubusercontent.com/22965241/113497982-938aa980-94bd-11eb-8c3b-a82ca8513e5a.png">

**Comment by KasparRosin** [comment]
Merged #89 and released version 2.1.0.

Thank you for reporting.
