### ISSUE TITLE
Class name must be a valid object or a string (after upgrade to 2.1.0)

### ISSUE THREAD

**Issue by mgralikowski** [optimistdigital/nova-multiselect-field#96]
Hi,

this stopped working:
```
Multiselect::make('Categories', 'categories')->belongsToMany(NewsCategory::class, false),
```
I think it is associated with this PR: https://github.com/optimistdigital/nova-multiselect-field/pull/89 @shawnheide

The error I get is:
`Class name must be a valid object or a string`
and it comes from new method `setOptionsFromModels` as `$this->resourceClass` returns null.

**Comment by KasparRosin** [comment]
This seemed to have happened when using `belongsTo` without async. 
I released version 2.1.1 that includes the fix.
