### ISSUE TITLE
CSS is broken dropdown container

### ISSUE THREAD

**Issue by iCONIC0** [optimistdigital/nova-multiselect-field#98]
Option container is broken and show a dropdown icon on top right of resource, on new/edit .

nova-multiselect-field versión: 2.1.2
Versión de Nova: 3.8.4
Versión de PHP: 7.3.27
Versión de Laravel: 7.30.4

<img width="1009" alt="Captura de Pantalla 2021-05-03 a la(s) 13 22 37" src="https://user-images.githubusercontent.com/12708525/116909773-ae625200-ac12-11eb-8c3f-57f00341eb2e.png">

**Comment by Tarpsvo** [comment]
Hi! Is still happening?
